type: Microsoft.App/ContainerApps
template:
  containers:
  - name: redis
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    env:
    - name: TCP_PORT
      value: 6379
    - name: ALLOW_EMPTY_PASSWORD
      value: 'yes'
  - name: vote
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    env:
    - name: HTTP_PORT
      value: 80
    - name: REDIS
      value: localhost
  scale:
    maxReplicas: 1
    minReplicas: 1
managedEnvironmentId: /subscriptions/e4847ba9-5afa-46c4-a287-17317c49d18f/resourceGroups/rg-aca-multicontainer/providers/Microsoft.App/managedEnvironments/containerapps-env-dev 
configuration:
  activeRevisionsMode: Multiple
  ingress:
    external: true
    allowInsecure: false
    targetPort: 80
